//
// Generated file, do not edit! Created by opp_msgtool 6.0 from distanceVector.msg.
//

#ifndef __DISTANCEVECTOR_M_H
#define __DISTANCEVECTOR_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

struct DistanceEntry;
class DistanceVectorMsg;
/**
 * Struct generated from distanceVector.msg:1 by opp_msgtool.
 */
struct DistanceEntry
{
    DistanceEntry();
    int destination = 0;
    int cost = 0;
};

// helpers for local use
void __doPacking(omnetpp::cCommBuffer *b, const DistanceEntry& a);
void __doUnpacking(omnetpp::cCommBuffer *b, DistanceEntry& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DistanceEntry& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DistanceEntry& obj) { __doUnpacking(b, obj); }

/**
 * Class generated from <tt>distanceVector.msg:5</tt> by opp_msgtool.
 * <pre>
 * message DistanceVectorMsg
 * {
 *     int senderId;
 *     DistanceEntry distanceVector[];
 * }
 * </pre>
 */
class DistanceVectorMsg : public ::omnetpp::cMessage
{
  protected:
    int senderId = 0;
    DistanceEntry *distanceVector = nullptr;
    size_t distanceVector_arraysize = 0;

  private:
    void copy(const DistanceVectorMsg& other);

  protected:
    bool operator==(const DistanceVectorMsg&) = delete;

  public:
    DistanceVectorMsg(const char *name=nullptr, short kind=0);
    DistanceVectorMsg(const DistanceVectorMsg& other);
    virtual ~DistanceVectorMsg();
    DistanceVectorMsg& operator=(const DistanceVectorMsg& other);
    virtual DistanceVectorMsg *dup() const override {return new DistanceVectorMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);

    virtual void setDistanceVectorArraySize(size_t size);
    virtual size_t getDistanceVectorArraySize() const;
    virtual const DistanceEntry& getDistanceVector(size_t k) const;
    virtual DistanceEntry& getDistanceVectorForUpdate(size_t k) { return const_cast<DistanceEntry&>(const_cast<DistanceVectorMsg*>(this)->getDistanceVector(k));}
    virtual void setDistanceVector(size_t k, const DistanceEntry& distanceVector);
    virtual void insertDistanceVector(size_t k, const DistanceEntry& distanceVector);
    [[deprecated]] void insertDistanceVector(const DistanceEntry& distanceVector) {appendDistanceVector(distanceVector);}
    virtual void appendDistanceVector(const DistanceEntry& distanceVector);
    virtual void eraseDistanceVector(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DistanceVectorMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DistanceVectorMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

inline any_ptr toAnyPtr(const DistanceEntry *p) {return any_ptr(p);}
template<> inline DistanceEntry *fromAnyPtr(any_ptr ptr) { return ptr.get<DistanceEntry>(); }
template<> inline DistanceVectorMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<DistanceVectorMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __DISTANCEVECTOR_M_H

