//
// Generated file, do not edit! Created by opp_msgtool 6.0 from hello.msg.
//

#ifndef __HELLO_M_H
#define __HELLO_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Hello;
/**
 * Class generated from <tt>hello.msg:1</tt> by opp_msgtool.
 * <pre>
 * packet Hello
 * {
 *     int senderID;
 * }
 * </pre>
 */
class Hello : public ::omnetpp::cPacket
{
  protected:
    int senderID = 0;

  private:
    void copy(const Hello& other);

  protected:
    bool operator==(const Hello&) = delete;

  public:
    Hello(const char *name=nullptr, short kind=0);
    Hello(const Hello& other);
    virtual ~Hello();
    Hello& operator=(const Hello& other);
    virtual Hello *dup() const override {return new Hello(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSenderID() const;
    virtual void setSenderID(int senderID);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Hello& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Hello& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Hello *fromAnyPtr(any_ptr ptr) { return check_and_cast<Hello*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __HELLO_M_H

